<?php
define('Push_Bd_Token','');
define('Push_Xz_Appid','');
define('Push_Xz_Token','');
define('Push_Sm_User','');
define('Push_Sm_Token','');
define('Push_Host','');
define('Push_Type','bd');
define('Push_Add_Mode',0);
define('Push_Cj_Mode',0);